on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jayacrdemo.azurecr.io
        username: ${{ secrets.acr_jayacrdemo_username }}
        password: ${{ secrets.acr_jayacrdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jayacrdemo.azurecr.io/jayaksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push jayacrdemo.azurecr.io/jayaksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jayaksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jayaksdemo9cfa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jayaksdemo9cfa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jayaksdemo9cfa
        container-registry-url: jayacrdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_jayacrdemo_username }}
        container-registry-password: ${{ secrets.acr_jayacrdemo_password }}
        secret-name: jayaksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jayaksdemo9cfa
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
          manifests/ingress-2.yml
        images: |
          jayacrdemo.azurecr.io/jayaksdemo:${{ github.sha }}
        imagepullsecrets: |
          jayaksdemodockerauth
